version: '3.4'
services:
  fluentsearch-insight-video:
    container_name: FluentSearch-Insight-Video
    restart: always
    environment:
      RABBITMQ_ENDPOINT: 'rabbitmq'
      RABBITMQ_USERNAME: 'root'
      RABBITMQ_PASSWORD: 'FluentSearchRabbitMQ'
      DATABASE_CONNECTION: 'mongodb://fluentsearch-bff-mongos/fluentsearch'
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: FluentSearch@BFF.MongoDB
      DATABASE_AUTH_SOURCE: admin
      PORT: 3001
      ORIGIN: 'true'
      ML_ENDPOINT: http://deepdetect:8080
      MINIO_ACCESS_KEY: 'root'
      MINIO_SECRET_KEY: '12345678'
      MINIO_SERVER_ENDPOINT: 'minio'
      MINIO_SERVER_PORT: 9000
      MINIO_SERVER_SSL: 'false'
      TMP_VIDEO_SERVER: http://fluentsearch-insight-video:3001
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3001:3001'
      - '9229:9229'
    volumes:
      - './src:/home/src'
      - './sample:/home/sample'
      - './tmp-app/:/home/tmp-app'
    logging:
      options:
        max-size: 50m
  deepdetect:
    container_name: deepdetect
    restart: on-failure
    image: jolibrain/deepdetect_cpu
    ports:
      - '8080:8080'
    volumes:
      - './models:/opt/models/'
  rabbitmq:
    image: bitnami/rabbitmq:3.8
    volumes:
      - ./mq/:/bitnami
    ports:
      - '15672:15672'
    environment:
      TZ: Asia/Bangkok
      RABBITMQ_USERNAME: root
      RABBITMQ_PASSWORD: FluentSearchRabbitMQ
  fluentsearch-bff-mongos:
    image: 'bitnami/mongodb-sharded:4.4'
    restart: on-failure
    environment:
      MONGODB_ADVERTISED_HOSTNAME: fluentsearch-bff-mongos
      MONGODB_SHARDING_MODE: mongos
      MONGODB_CFG_PRIMARY_HOST: fluentsearch-bff-cfg
      MONGODB_CFG_REPLICA_SET_NAME: fluentsearch-bff-cfg
      MONGODB_REPLICA_SET_KEY: fluentsearchbff
      MONGODB_ROOT_PASSWORD: FluentSearch@BFF.MongoDB
      TZ: Asia/Bangkok
    ports:
      - '27017:27017'
  fluentsearch-bff-shard:
    image: 'bitnami/mongodb-sharded:4.4'
    restart: on-failure
    environment:
      MONGODB_ADVERTISED_HOSTNAME: fluentsearch-bff-shard
      MONGODB_SHARDING_MODE: shardsvr
      MONGODB_MONGOS_HOST: fluentsearch-bff-mongos
      MONGODB_ROOT_PASSWORD: FluentSearch@BFF.MongoDB
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: fluentsearchbff
      MONGODB_REPLICA_SET_NAME: fluentsearch-shard0
      TZ: Asia/Bangkok
    volumes:
      - './db/shard-0:/bitnami'
  fluentsearch-bff-cfg:
    image: 'bitnami/mongodb-sharded:4.4'
    restart: on-failure
    environment:
      MONGODB_ADVERTISED_HOSTNAME: fluentsearch-bff-cfg
      MONGODB_SHARDING_MODE: configsvr
      MONGODB_ROOT_PASSWORD: FluentSearch@BFF.MongoDB
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: fluentsearchbff
      MONGODB_REPLICA_SET_NAME: fluentsearch-cfg
      TZ: Asia/Bangkok
    volumes:
      - './db/cfg:/bitnami'
  minio:
    image: bitnami/minio:latest
    environment:
      MINIO_ACCESS_KEY: 'root'
      MINIO_SECRET_KEY: '12345678'
      MINIO_SERVER_HOST: 'minio'
    ports:
      - '9000:9000'
