version: '3.4'
services:
  fluentsearch-insight-video:
    container_name: FluentSearch-Insight-Video
    restart: always
    environment:
      PORT: 3001
      ORIGIN: 'true'
      ML_ENDPOINT: http://insight:8080
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - './src:/home/src'
      - './sample:/home/sample'
      - './tmp-app/:/home/tmp-app'
    logging:
      options:
        max-size: 50m
  deepdetect:
    container_name: deepdetect
    restart: on-failure
    image: jolibrain/deepdetect_cpu
    ports:
      - '8080:8080'
    volumes:
      - './models:/opt/models/'

  rabbitmq:
    image: bitnami/rabbitmq:3.8
    volumes:
      - ./mq/:/bitnami
    ports:
      - '15672:15672'
    environment:
      TZ: Asia/Bangkok
      RABBITMQ_USERNAME: root
      RABBITMQ_PASSWORD: FluentSearchRabbitMQ
